baseline: Sound Engineer
theme:
  - hyde
  - netlify
  - netlify-cms
keywords:
  - Cecil
  - Static Site Generator
  - SSG
author: Yanna
date:
  format: j F Y
  timezone: Europe/Brussels
hyde:
  sidebar:
    sticky: true
  theme: ""
  reverse: false
title: Yanna Soentjens
description: Sound Engineer
baseurl: /
canonicalurl: true
